mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_USER=fitness_stack
      - MYSQL_PASSWORD=dabest_trabalho
      - MYSQL_ROOT_PASSWORD=fitstack_secretpw
      - MYSQL_TCP_PORT= 3307
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3307:3307